# Generated by Django 4.2.13 on 2024-05-31 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrovanikorisnik',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('brojtelefona', models.CharField(db_column='BrojTelefona', max_length=20)),
                ('datumrodjenja', models.DateTimeField(db_column='DatumRodjenja')),
                ('mestorodjenja', models.CharField(db_column='MestoRodjenja', max_length=20)),
                ('brojkartice', models.CharField(db_column='BrojKartice', max_length=16)),
                ('slika', models.ImageField(db_column='Slika', default='profile_images/default.jpg', upload_to='profile_images/')),
                ('prodatihNFT', models.IntegerField(db_column='prodatihNft', default=0)),
                ('kupljenihNFT', models.IntegerField(db_column='kupljenihNft', default=0)),
                ('datumkreiranja', models.DateField(blank=True, db_column='DatumKreiranja', null=True)),
            ],
            options={
                'db_table': 'registrovanikorisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kolekcionar',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'kolekcionar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kreator',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'kreator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'kupac',
                'managed': True,
            },
        ),
    ]
