# Generated by Django 4.2.13 on 2024-05-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nft', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listanft',
            fields=[
                ('idlis', models.AutoField(db_column='IdLis', primary_key=True, serialize=False)),
                ('ukupnavrednost', models.FloatField(db_column='UkupnaVrednost')),
                ('brojnft', models.IntegerField(db_column='BrojNFT')),
                ('idvla', models.ForeignKey(db_column='IdVla', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'listanft',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Izlozba',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exhibitions.listanft')),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=18, null=True)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=1024, null=True)),
                ('datumkreiranja', models.CharField(blank=True, db_column='DatumKreiranja', max_length=18, null=True)),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'izlozba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kolekcija',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'kolekcija',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'portfolio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pripada',
            fields=[
                ('idpri', models.AutoField(db_column='IdPri', primary_key=True, serialize=False)),
                ('idlis', models.ForeignKey(db_column='IdLis', on_delete=django.db.models.deletion.CASCADE, to='exhibitions.listanft')),
                ('idnft', models.ForeignKey(db_column='IdNFT', on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
            options={
                'db_table': 'pripada',
                'managed': True,
            },
        ),
    ]
