# Generated by Django 4.2.13 on 2024-05-31 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idkor', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('user_type', models.CharField(default='guest', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zahtevzaregistraciju',
            fields=[
                ('idzah', models.AutoField(db_column='IdZah', primary_key=True, serialize=False)),
                ('korime', models.CharField(db_column='KorIme', default='', max_length=32)),
                ('sifra', models.CharField(db_column='Sifra', max_length=128, null=True)),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('brojtelefona', models.CharField(db_column='BrojTelefona', max_length=20)),
                ('datumrodjenja', models.DateField(db_column='DatumRodjenja')),
                ('mestorodjenja', models.CharField(db_column='MestoRodjenja', max_length=20)),
                ('brojkartice', models.CharField(db_column='BrojKartice', max_length=16)),
                ('uloga', models.CharField(blank=True, db_column='Uloga', max_length=11, null=True)),
            ],
            options={
                'db_table': 'zahtevzaregistraciju',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrator',
                'managed': True,
            },
        ),
    ]
